// Playable aircraft and their flight/combat stats.
//
// speeds in m/s, rates in rad/s, thrust as acceleration (m/s²).
// maxSpeed is the level-flight top speed with afterburner; military power
// alone tops out around 80 % of it.

export const AIRCRAFT = {
  viper: {
    id: 'viper',
    name: 'F/A-41 Viper',
    role: 'Agile fighter',
    design: 'viper',
    price: 0,
    description: 'Balanced air-superiority fighter. Best turn rate and roll response in the hangar.',
    hp: 100,
    maxSpeed: 330,
    thrust: 46,
    abThrust: 30,
    stallSpeed: 62,
    cornerSpeed: 190,
    pitchRate: 1.95,
    rollRate: 4.4,
    yawRate: 0.7,
    maxG: 9.5,
    response: 7,
    induced: 0.07,
    brake: 0.035,
    radarRange: 9000,
    lockSpeed: 1,
    signature: 1,
    slots: 3,
    hardpointMult: 1,
    radius: 9,
    camDistance: 26,
  },
  hammer: {
    id: 'hammer',
    name: 'A/F-60 Hammer',
    role: 'Heavy striker',
    design: 'hammer',
    price: 6000,
    description: 'Armoured strike jet. Carries 60 % more air-to-ground ordnance and takes a beating. Slow to turn.',
    hp: 190,
    maxSpeed: 285,
    thrust: 38,
    abThrust: 24,
    stallSpeed: 58,
    cornerSpeed: 170,
    pitchRate: 1.35,
    rollRate: 2.9,
    yawRate: 0.55,
    maxG: 7,
    response: 5,
    induced: 0.08,
    brake: 0.04,
    radarRange: 8500,
    lockSpeed: 0.9,
    signature: 1.2,
    slots: 3,
    hardpointMult: 1.6,
    radius: 11,
    camDistance: 30,
  },
  wraith: {
    id: 'wraith',
    name: 'X-77 Wraith',
    role: 'Stealth jet',
    design: 'wraith',
    price: 9000,
    description: 'Low radar signature: enemies take far longer to lock on and SAMs lose track easily. Lighter armour.',
    hp: 85,
    maxSpeed: 315,
    thrust: 44,
    abThrust: 26,
    stallSpeed: 60,
    cornerSpeed: 185,
    pitchRate: 1.7,
    rollRate: 3.8,
    yawRate: 0.65,
    maxG: 8.5,
    response: 6.5,
    induced: 0.07,
    brake: 0.035,
    radarRange: 9500,
    lockSpeed: 1.2,
    signature: 0.4,
    slots: 3,
    hardpointMult: 0.9,
    radius: 9,
    camDistance: 26,
  },
  lancer: {
    id: 'lancer',
    name: 'MiR-35 Lancer',
    role: 'Interceptor',
    design: 'lancer',
    price: 7500,
    description: 'Fastest jet in service with a long-range radar and quick missile locks. Wide turns.',
    hp: 110,
    maxSpeed: 400,
    thrust: 54,
    abThrust: 40,
    stallSpeed: 72,
    cornerSpeed: 220,
    pitchRate: 1.45,
    rollRate: 3.5,
    yawRate: 0.55,
    maxG: 8,
    response: 6,
    induced: 0.06,
    brake: 0.03,
    radarRange: 14000,
    lockSpeed: 1.45,
    signature: 1,
    slots: 3,
    hardpointMult: 1,
    radius: 10,
    camDistance: 28,
  },
};

export const AIRCRAFT_ORDER = ['viper', 'hammer', 'wraith', 'lancer'];

export const PAINTS = {
  gunmetal: { name: 'Gunmetal', color: 0x4c535c, price: 0 },
  arctic: { name: 'Arctic', color: 0xb8c2cc, price: 300 },
  navy: { name: 'Navy Blue', color: 0x24344e, price: 300 },
  desert: { name: 'Desert', color: 0x9b8462, price: 300 },
  forest: { name: 'Forest', color: 0x3d4a35, price: 300 },
  stealth: { name: 'Stealth Black', color: 0x1c1e22, price: 600 },
  crimson: { name: 'Crimson', color: 0x7a1e1e, price: 800 },
  aggressor: { name: 'Aggressor Blue', color: 0x5a7a9e, price: 800 },
  gold: { name: 'Ace Gold', color: 0xa8873c, price: 2500 },
};
